# Site settings
title: Think Olson
header-img: img/home-bg.jpg
email: will.olson11@gmail.com
copyright_name: ThinkOlson.com
description: "A cool place for my thoughts and projects"
baseurl: ""
url: "https://frankolson.github.io"
twitter_username: thinkolson
github_username:  frankolson
facebook_username:  will.olson11
email_username:  will.olson11@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
paginate_path: "/blog/page:num/"
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

plugins: [jekyll-paginate, jekyll-feed]
